server:
  port: 9003

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

service-url:
  nacos-user-service: http://nacos-provider
  nacos-config-service: http://nacos-config-client
